[receiver]
[receiver.web]
error    = "http://localhost:8000/error"
success  = "http://localhost:8000/success"

[notify]
[[notify.email]]
from = "noreplay@example.com"
to = "example@example.com"
title = "タイトル"
[notify.email.smtp]
host = "localhost"
port = "587"
user = ""
password = ""
[[notify.slack]]
token = "example_token"
channel = "#example_channel"
username = "example name"
as_user = true
unfurl_links = true
unfurl_media = true
icon_url = "http://example.com/example.xxx"
icon_emoji = ":example:"
