[receiver]
[receiver.web]
[[receiver.web.form]]
name     = "foo"
error    = "http://localhost:8000/error"
success  = "http://localhost:8000/success"
supported_fields = "名前,趣味,ファイル,秘密書類"
supported_file_extentions = ".pdf,.txt,.csv"

[[receiver.web.form]]
name     = "bar"
error    = "http://localhost:8000/error"
success  = "http://localhost:8000/success"
supported_fields = "名前,趣味,夢"

[filter]
format = "html"
[filter.html]
template = "assets/config/template/example.html"

[notify]
[[notify.email]]
from = "noreplay@example.com"
to = "example@example.com"
cc = "example@example.com,example2@example.com"
title = "タイトル"
[notify.email.smtp]
host = "localhost"
port = "587"
user = ""
password = ""
[[notify.slack]]
token = "example_token"
channel = "#example_channel"
username = "example name"
as_user = true
unfurl_links = true
unfurl_media = true
icon_url = "http://example.com/example.xxx"
icon_emoji = ":example:"
