[receiver]
[receiver.web]
[receiver.web.form.foo]
error = "http://localhost:8000/error"
success = "http://localhost:8000/success"
supported_fields = "名前,趣味,ファイル,秘密書類"
supported_file_extentions = ".pdf,.txt,.csv"
notifiers="email.bar"
title = "自己紹介フォーム"

[receiver.web.form.bar]
error = "http://localhost:8000/error"
success = "http://localhost:8000/success"
supported_fields = "名前,趣味,夢"
notifiers="email.bar,slack.bar"
title = "夢ふぉーむ"

[filter]
[filter.bar]
format = "html"
template = "/foo/bar.tmpl"
[filter.foo]
format = "text"

[notify]
[notify.email.bar]
from = "noreplay@example.com"
to = "example@example.com"
cc = "example@example.com,example2@example.com"
filter = "bar"
[notify.email.bar.smtp]
host = "localhost"
port = "587"
user = ""
password = ""

[notify.slack.bar]
token = "example_token"
channel = "#example_channel"
username = "example name"
as_user = true
unfurl_links = true
unfurl_media = true
icon_url = "http://example.com/example.xxx"
icon_emoji = ":example:"
filter = "foo"
